### ISSUE TITLE
Failed to load 'Assets/ViveMediaDecoder/Plugins/x86_64/ViveMediaDecoder.dll' 

### ISSUE THREAD

**Issue by natsupy** [ViveSoftware/ViveMediaDecoder#11]
I was testing on Win10 and Unity 2017.1 have that warning, so anyone can help to fix that
![image](https://user-images.githubusercontent.com/15712687/32707077-f9605c1c-c853-11e7-8b00-dc7f3613137f.png)

**Comment by kyo8568131** [comment]
Hi,
Please help to check the environment and follow the readme.txt to set up the dlls.
And please note that this plugin only support Windows platform while your build settings choose Android.
Thanks.

**Comment by natsupy** [comment]
Hi, thank you for reply, I was check on stand_alone but have the same issue, so what am I mistaken, can you help
![image](https://user-images.githubusercontent.com/15712687/32760607-a1e16304-c921-11e7-9c4c-986f2614252c.png)

**Comment by kyo8568131** [comment]
Do you put the 64 bits FFmpeg dlls into plugin/x86_64/ ?

**Comment by natsupy** [comment]
I was, the warning is missing Vive dll, I don't think about ffmpeg dll

![image](https://user-images.githubusercontent.com/15712687/32761922-cb679ae8-c928-11e7-92ad-90da6d0a6254.png)

**Comment by kyo8568131** [comment]
The warning massage only shows the errors about the dll which Unity is using.
So it would only show "Failed to load CurrentDll.dll" if any native dependent dlls miss.
Please copy the FFmpeg dlls, which includes avcodec-57.dll, avformat-57.dll, avutil-55.dll and swresample-2.dll, into the Plugins/x86_64/.
You could check the readme.txt for further information.
Thanks.

**Comment by natsupy** [comment]
Ah thank you, my bad.
