### ISSUE TITLE
Failed to load specific module from the ViveMediaDecoder.dll

### ISSUE THREAD

**Issue by spaul13** [ViveSoftware/ViveMediaDecoder#22]
After linking with the FFmpeg in the visual studio, I somehow generated my own .dll for x86_64 not changing any part of native DLL project but while using that dll as a native plugin to Unity, It's showing me the following error of **_" failed to load specific module"_**

Error log:
_Failed to load 'Assets/Plugins/x86_64/ViveMediaDecoder.dll' with error 'The specified module could not be found.
'.
RtlLookupFunctionEntry returned NULL function. Aborting stack walk.
0x00000001417CC67B (Unity) StackWalker::GetCurrentCallstack
0x00000001417CE35F (Unity) StackWalker::ShowCallstack
0x00000001417A8350 (Unity) GetStacktrace
0x0000000140D5520B (Unity) DebugStringToFile
0x0000000140D559EC (Unity) DebugStringToFile
0x0000000140DA521D (Unity) PlayerSettings::InitDefaultCursors
0x0000000140DB33F5 (Unity) FindAndLoadUnityPlugin
0x00007FFE8CF59A21 (mono) [loader.c:1298] mono_lookup_pinvoke_call 
0x00007FFE8CF6D151 (mono) [marshal.c:8122] mono_marsha_get_native_wrapper 
0x00007FFE8D01379B (mono) [method-to-ir.c:6435] mono_method_to_ir 
0x00007FFE8D033F70 (mono) [mini.c:3590] mini_method_compile 
0x00007FFE8D03503B (mono) [mini.c:4344] mono_jit_compile_method_inner 
0x00007FFE8D035659 (mono) [mini.c:4556] mono_jit_compile_method_with_opt 
0x00007FFE8D0356EC (mono) [mini.c:4580] mono_jit_compile_method 
0x00007FFE8D02D7C3 (mono) [mini-trampolines.c:477] mono_magic_trampoline 
<Missing stacktrace information>_

E.g. all the required ffmpeg dlls are kept in Plugins/x86-64/ already. Can anyone please help me what modules I am missing and how to resolve this issue?

**Comment by kyo8568131** [comment]
Hi spaul13,

Which version of FFmpeg library do you use?
Please help to check the library version to be consistent.
Thanks.

**Comment by spaul13** [comment]
This one got resolved. Thanks a lot @kyo8568131
